### PR TITLE
Fix compatibility with py2; pep8 in patches.py

### PR DESCRIPTION
**Pull request by tiberiuichim**

### CODE REVIEW

**Comment by tisto** [comment]
@tiberiuichim would you mind elaborating why this fixes py2 compatibility? I see the pep8 fixes but I miss the lines that would fix py2.

**Comment by tiberiuichim** [comment]
```
title="Frontend domain"
```
As far as I remember (we've started using py3 everywhere), the problem was the one above. The titles need to be unicode, so in py2 it would spit out an error, it needs to be: ``title = u"Frontend domain"``.

**Comment by tisto** [comment]
@tiberiuichim thanks for the clarification! That was hard to spot. :)

**Comment by tisto** [comment]
@tiberiuichim thanks for your contribution and sorry for not taking care of merging for such a long time.

**Pull request merged**
